name: fooddelivery
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.4.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^9.2.1+1
  flutter_svg: ^2.0.10+1
  alpha_ui:
    git: https://github.com/alpha-sow/alpha_ui.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.6.0

flutter_gen:
  output: lib/assets/

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
